name: "Deploy v3 docs"
on:
  push:
    branches:
      - v3

env:
  CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}

jobs:
  v3-docs:
    runs-on: ubuntu-latest
    steps:
      - name: setup actions
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
          registry-url: https://registry.npmjs.org
      - name: install malta
        working-directory: docs
        run: |
          curl -o malta.tgz -L https://github.com/pilcrowonpaper/malta/releases/latest/download/linux-amd64.tgz
          tar -xvzf malta.tgz
      - name: build
        working-directory: docs
        run: ./linux-amd64/malta
      - name: install wrangler
        run: npm i -g wrangler
      - name: deploy
        run: wrangler pages deploy docs/dist --project-name lucia-v3 --branch main
